export const FETCH_RENTALS = 'FETCH_RENTALS';
export const FETCH_RENTAL_BY_ID = 'FETCH_RENTAL_BY_ID';
export const FETCH_RENTAL_BY_ID_SUCSESS = 'FETCH_RENTAL_BY_ID_SUCSESS';
export const FETCH_RENTALS_SUCSESS = 'FETCH_RENTALS_SUCSESS'
